server:
  port: 8080
  context-path: "/"

logging:
  level:
    org:
      springframework:
        web: DEBUG

spring:
  security:
    user:
      name: user
      password: password
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    generate-unique-name: false