server:
  port: 8080
  servlet:
    context-path: /ims

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    com.app.ims: DEBUG
    org.hibernate: ERROR


spring:
  security:
    user:
      name: user
      password: password
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    generate-unique-name: false

  jpa:
    generate-ddl: true

    hibernate:
      ddl-auto: update

#springdoc:
#  swagger-ui:
#    path: /v2/swagger-ui.html