# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: IMS-Build-Workflow

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, feature/* , custom/*, bugfix/*, hotfix/* ]
  pull_request:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build
      run: mvn clean install
    - name: Test
      run: mvn spring-boot:run
